#Blank Job Bio Data Format Design#
print("\n----------------------------------------------------------------------------------------|\n|")
print("|\t\t\t\tBIO DATA\t\t\t\t\t\t|\n|")
print("|Name\t\t\t:\t ___________________\t\t\t\t\t|\n|")
print("|Mobile\t\t\t:\t ___________________\t\t\t\t\t|\n|")
print("|Email id\t\t:\t ___________________\t\t\t\t\t|\n|")
print("|Father's Name\t\t:\t ___________________\t\t\t\t\t|\n|")
print("|Gender\t\t\t:\t ___________________\t\t\t\t\t|\n|")
print("|Date of Birth\t\t:\t ___________________\t\t\t\t\t|\n|")
print("|Marital Status\t\t:\t ___________________\t\t\t\t\t|\n|")
print("|Religion\t\t:\t ___________________\t\t\t\t\t|\n|")
print("|Languages Known\t:\t ___________________\t\t\t\t\t|\n|")
print("|Qualification\t\t:\t _________________________________\t\t\t|\n|")
print("|Experience\t\t:\t _________________________________\t\t\t|\n|")
print("|Address\t\t:\t _________________________________\t\t\t|\n|")
print("|Place\t\t\t:\t _________________________________\t\t\t|\n|")
print("|Date\t\t\t:\t\t\t\t\t___________________\t|")
print("|\t\t\t\t\t\t\t\tSigniture\t\t|\n|")
print("|----------------------------------------------------------------------------------------")